services:
  client:
    container_name: client
    build: ./client/
    network_mode: "host" 
    environment:
      SERVER_IP: localhost
    volumes:
      - ./client:/client
    depends_on:
      - server
    restart: on-failure:3 
  

  server:
    container_name: server
    build: ./server/
    network_mode: "host" 
    volumes:
      - ./server:/server